// Compatibility barrel. New code should import from ./domains/<domain> directly.
export * from './domains/metadata'
export * from './domains/development'
export * from './domains/integration'
export * from './domains/workflow'
export * from './domains/operations'
export * from './domains/runtime'
export * from './domains/release'
export * from './domains/metrics'
export * from './domains/assets'
export type { DataSourceView } from './platform'
