<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { Graph } from '@antv/x6'
import { ElMessage } from 'element-plus'
import { Search } from '@element-plus/icons-vue'
import { useRoute, useRouter } from 'vue-router'
import { developmentApi, integrationApi, releaseApi, workflowApi, type DevFile, type DevelopmentSchedule, type IntegrationTask, type IntegrationTaskSchedule, type WorkflowNode, type WorkflowView } from '../../api/domain'

type NodeKind='SQL'|'PYTHON'|'SHELL'|'SEATUNNEL'|'CONDITION'
type TaskFilter='ALL'|'DEV'|'OFFLINE'|'SQL'|'PYTHON'|'SHELL'
type InspectorTab='prop'|'schedule'|'dep'
type NodeData={name:string;nodeType:NodeKind;devFileId?:number;integrationTaskId?:number;configJson:string;taskVersion?:number;lifecycleStatus?:string;ownerName?:string}

const route=useRoute(),router=useRouter()
const loading=ref(true),rows=ref<WorkflowView[]>([]),sharedGraph=ref<WorkflowView>(),editorOpen=ref(false),sharedMode=ref(false),saving=ref(false),dirty=ref(false)
const current=ref<WorkflowView|null>(null),files=ref<DevFile[]>([]),integrationTasks=ref<IntegrationTask[]>([])
const selectedCode=ref(''),selectedEdgeId=ref(''),selectedSchedule=ref<DevelopmentSchedule>(),selectedIntegrationSchedule=ref<IntegrationTaskSchedule>()
const listSearch=ref(''),statusFilter=ref('ALL'),taskSearch=ref(''),taskFilter=ref<TaskFilter>('ALL'),inspectorTab=ref<InspectorTab>('prop')
const canvasRef=ref<HTMLDivElement>(),graphScale=ref(1),graphRevision=ref(0)
const form=reactive({name:'',description:''}),nodeDraft=reactive<NodeData>({name:'',nodeType:'SQL',configJson:'{}'}),conditionExpression=ref("status == 'SUCCESS'")
const stats=reactive({nodes:0,edges:0,roots:0,leaves:0})
let graph:Graph|undefined
function stripExt(v:string){return (v||'').replace(/\.(sql|sh|py)$/i,'')}
function msg(e:unknown){return e instanceof Error?e.message:'操作失败'}
function typeLabel(v?:string){return ({SQL:'SQL',PYTHON:'Python',SHELL:'Shell',SEATUNNEL:'SeaTunnel',CONDITION:'条件'} as Record<string,string>)[v||'']||v||'任务'}
function lifecycleLabel(v?:string){return v==='ONLINE'?'已上线':'未上线'}
function cycleLabel(v?:string){return ({DAILY:'每日',HOURLY:'每小时',WEEKLY:'每周',MONTHLY:'每月',CRON:'Cron'} as Record<string,string>)[v||'']||v||'—'}
function statusLabel(v?:string){return v==='PUBLISHED'?'已发布':v==='RUNNING'?'运行中':v==='SYNCED'?'已同步':'草稿'}
function statusClass(v?:string){return v==='PUBLISHED'||v==='SYNCED'?'green':v==='RUNNING'?'blue':'orange'}
function fmt(v?:string){if(!v)return'—';const d=new Date(v);if(Number.isNaN(d.getTime()))return v;return d.toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})}
function parseConfig(v?:string){try{return JSON.parse(v||'{}') as Record<string,unknown>}catch{return {}}}
function integrationId(v?:string){const n=Number(parseConfig(v).integrationTaskId||0);return n>0?n:undefined}
function integrationRoute(t?:IntegrationTask){const x=t?.tables?.[0];return x?`${x.sourceDatabase}.${x.sourceTable} → ${x.targetDatabase}.${x.targetTable}`:(t?`${t.sourceType} → ${t.targetType}`:'未绑定离线同步任务')}
function integrationMode(t?:IntegrationTask){return ({FULL:'全量',INCREMENTAL:'增量',FULL_INCREMENTAL:'全量 + 增量'} as Record<string,string>)[t?.syncMode||'']||t?.syncMode||'—'}

const workflowRows=computed(()=>{const all=[...(sharedGraph.value?[sharedGraph.value]:[]),...rows.value],q=listSearch.value.trim().toLowerCase();return all.filter(w=>(!q||w.name.toLowerCase().includes(q)||w.workflowCode.toLowerCase().includes(q))&&(statusFilter.value==='ALL'||w.status===statusFilter.value))})
const filteredDevTasks=computed(()=>files.value.filter(f=>{if(sharedMode.value&&f.fileType?.toUpperCase()!=='SQL')return false;if(taskFilter.value==='OFFLINE')return false;if(['SQL','PYTHON','SHELL'].includes(taskFilter.value)&&f.fileType?.toUpperCase()!==taskFilter.value)return false;const q=taskSearch.value.trim().toLowerCase();return !q||f.name.toLowerCase().includes(q)||(f.ownerName||'').toLowerCase().includes(q)}))
const filteredOfflineTasks=computed(()=>{if(sharedMode.value||['DEV','SQL','PYTHON','SHELL'].includes(taskFilter.value))return[];const q=taskSearch.value.trim().toLowerCase();return integrationTasks.value.filter(t=>!q||t.name.toLowerCase().includes(q)||integrationRoute(t).toLowerCase().includes(q))})
const taskCount=computed(()=>filteredDevTasks.value.length+filteredOfflineTasks.value.length)
const selectedDevFile=computed(()=>nodeDraft.devFileId?files.value.find(f=>f.id===nodeDraft.devFileId):undefined)
const selectedIntegrationTask=computed(()=>nodeDraft.integrationTaskId?integrationTasks.value.find(t=>t.id===nodeDraft.integrationTaskId):undefined)
const selectedIsTask=computed(()=>Boolean(nodeDraft.devFileId||nodeDraft.integrationTaskId))
const selectedDependencies=computed(()=>{graphRevision.value;if(!graph||!selectedCode.value)return{ups:[],downs:[]};const nameOf=(id:string)=>{const n=graph?.getCellById(id);return n?.isNode()?((n.getData() as NodeData).name||id):id};return{ups:graph.getEdges().filter(e=>String(e.getTargetCellId())===selectedCode.value).map(e=>nameOf(String(e.getSourceCellId()))),downs:graph.getEdges().filter(e=>String(e.getSourceCellId())===selectedCode.value).map(e=>nameOf(String(e.getTargetCellId())))}})
const selectedEdgeInfo=computed(()=>{graphRevision.value;if(!graph||!selectedEdgeId.value)return undefined;const e=graph.getCellById(selectedEdgeId.value);if(!e?.isEdge())return undefined;const nameOf=(id:string)=>{const n=graph?.getCellById(id);return n?.isNode()?((n.getData() as NodeData).name||id):id};return{source:nameOf(String(e.getSourceCellId())),target:nameOf(String(e.getTargetCellId()))}})

async function load(){loading.value=true;try{rows.value=await workflowApi.list()}catch(e){ElMessage.error(msg(e))}finally{loading.value=false}}
async function loadSharedGraph(){try{sharedGraph.value=await workflowApi.developmentGraph()}catch(e){ElMessage.error('开发任务依赖图加载失败：'+msg(e))}}
async function loadTasks(){try{const ps=await developmentApi.projects();const [dev,offline]=await Promise.all([Promise.all(ps.map(p=>developmentApi.files(p.id))),integrationApi.list()]);files.value=dev.flat();integrationTasks.value=offline}catch(e){ElMessage.error('任务库加载失败：'+msg(e))}}
async function boot(){await Promise.all([load(),loadSharedGraph(),loadTasks()]);const focus=Number(route.query.fileId||0);if(focus)await openSharedGraph(focus)}

function newWorkflow(){sharedMode.value=false;current.value=null;form.name='';form.description='';selectedCode.value='';selectedEdgeId.value='';editorOpen.value=true;dirty.value=false;void nextTick(()=>initGraph())}
async function edit(row:WorkflowView){if(row.id===0)return openSharedGraph();try{sharedMode.value=false;current.value=await workflowApi.get(row.id);form.name=current.value.name;form.description=current.value.description||'';openEditor(current.value)}catch(e){ElMessage.error(msg(e))}}
async function openSharedGraph(focusFileId?:number){try{sharedMode.value=true;const view=await workflowApi.developmentGraph();sharedGraph.value=view;current.value=view;form.name=view.name;form.description=view.description||'';await openEditor(view,focusFileId)}catch(e){ElMessage.error(msg(e))}}
async function openEditor(view?:WorkflowView|null,focusFileId?:number){selectedCode.value='';selectedEdgeId.value='';selectedSchedule.value=undefined;selectedIntegrationSchedule.value=undefined;inspectorTab.value='prop';editorOpen.value=true;dirty.value=false;await nextTick();initGraph(view);if(focusFileId){const target=graph?.getNodes().find(n=>(n.getData() as NodeData)?.devFileId===focusFileId);if(target){graph?.centerCell(target);await selectNode(String(target.id))}}}
function closeEditor(){graph?.dispose();graph=undefined;editorOpen.value=false;sharedMode.value=false;selectedCode.value='';selectedEdgeId.value='';if(route.query.fileId)void router.replace({path:'/workflow/definitions'})}
function nodeVisual(data:NodeData){const dev=data.devFileId?files.value.find(f=>f.id===data.devFileId):undefined,off=data.integrationTaskId?integrationTasks.value.find(t=>t.id===data.integrationTaskId):undefined;const type=(dev?.fileType||data.nodeType||'SQL').toUpperCase();const icon=type==='PYTHON'?'PY':type==='SHELL'?'SH':type==='SEATUNNEL'?'ST':type==='CONDITION'?'◇':'SQL';const meta=dev?`V${dev.currentVersion} · ${lifecycleLabel(dev.lifecycleStatus)}`:off?integrationRoute(off):type==='CONDITION'?'条件控制节点':'未绑定离线同步任务';const online=dev?.lifecycleStatus==='ONLINE'||off?.lifecycleStatus==='ONLINE'||off?.status==='ENABLED';return{icon,meta,online,type}}
function initGraph(w?:WorkflowView|null){
  graph?.dispose();if(!canvasRef.value)return
  graph=new Graph({container:canvasRef.value,autoResize:true,background:{color:'#f7f8fb'},grid:{visible:true,size:18,type:'dot',args:{color:'#dfe5ed'}},panning:true,mousewheel:{enabled:true,modifiers:['ctrl','meta'],minScale:.7,maxScale:1.5},connecting:{connector:'smooth',anchor:'center',connectionPoint:'boundary',allowBlank:false,allowLoop:false,allowMulti:false,snap:true,createEdge(){return graph!.createEdge({zIndex:0,attrs:{line:{stroke:'#aeb7c4',strokeWidth:1.45,targetMarker:{name:'block',width:8,height:8}}}})}}})
  if(w){const idToCode=new Map(w.nodes.map(n=>[n.id,n.nodeCode]));w.nodes.forEach(n=>addGraphNode(n,false));w.edges.forEach(e=>{const s=idToCode.get(e.sourceNodeId),t=idToCode.get(e.targetNodeId);if(s&&t)graph?.addEdge({source:{cell:s,port:'out'},target:{cell:t,port:'in'},zIndex:0,attrs:{line:{stroke:'#aeb7c4',strokeWidth:1.45,targetMarker:{name:'block',width:8,height:8}}}})})}
  graph.on('node:click',({node})=>void selectNode(String(node.id)))
  graph.on('blank:click',()=>clearSelection())
  graph.on('node:moved',()=>{if(!sharedMode.value)dirty.value=true;updateStats()})
  graph.on('edge:connected',({edge})=>{if(!validateNewEdge(edge)){graph?.removeCell(edge);return}dirty.value=true;updateStats()})
  graph.on('edge:click',({edge})=>selectEdge(String(edge.id)))
  graph.on('edge:dblclick',({edge})=>{if(canChangeEdge(edge)){graph?.removeCell(edge);clearSelection();dirty.value=true;updateStats()}})
  graph.on('edge:removed',()=>updateStats())
  dirty.value=false;updateStats();setTimeout(()=>fit(),0)
}
function addGraphNode(n?:Partial<WorkflowNode>,select=true){if(!graph)return;const cfg=parseConfig(n?.configJson),integrationTaskId=Number(cfg.integrationTaskId||0)||undefined,dev=n?.devFileId?files.value.find(f=>f.id===n.devFileId):undefined,off=integrationTaskId?integrationTasks.value.find(t=>t.id===integrationTaskId):undefined;const code=n?.nodeCode||`node_${Date.now()}_${Math.random().toString(16).slice(2,7)}`;const nodeType=(n?.nodeType||dev?.fileType||(off?'SEATUNNEL':'CONDITION')) as NodeKind;const data:NodeData={name:n?.name||stripExt(dev?.name||off?.name||(nodeType==='CONDITION'?'条件分支':'SeaTunnel 节点')),nodeType,devFileId:n?.devFileId,integrationTaskId,configJson:n?.configJson||'{}',taskVersion:dev?.currentVersion,lifecycleStatus:dev?.lifecycleStatus,ownerName:dev?.ownerName};const v=nodeVisual(data)
  graph.addNode({id:code,x:n?.x??90+(graph.getNodes().length%3)*270,y:n?.y??90+Math.floor(graph.getNodes().length/3)*125,width:224,height:74,data,markup:[{tagName:'rect',selector:'body'},{tagName:'rect',selector:'iconBody'},{tagName:'text',selector:'iconText'},{tagName:'text',selector:'title'},{tagName:'text',selector:'meta'},{tagName:'circle',selector:'life'}],attrs:{body:{fill:'#fff',stroke:'#dfe4eb',strokeWidth:1,rx:8,ry:8},iconBody:{x:13,y:20,width:34,height:34,rx:9,ry:9,fill:v.type==='SEATUNNEL'?'#f7f5ff':v.type==='CONDITION'?'#f8fafc':'#f3f8ff',stroke:v.type==='SEATUNNEL'?'#e0d9fa':v.type==='CONDITION'?'#cad2dd':'#d2e1f8',strokeWidth:1},iconText:{text:v.icon,x:30,y:41,textAnchor:'middle',fontSize:10,fontWeight:800,fill:v.type==='SEATUNNEL'?'#6d55d8':v.type==='CONDITION'?'#687689':'#2f6fed'},title:{text:data.name,x:58,y:30,fontSize:12.5,fontWeight:600,fill:'#2d3b50',textAnchor:'start'},meta:{text:v.meta,x:58,y:50,fontSize:10,fill:'#8c97a8',textAnchor:'start'},life:{cx:207,cy:18,r:3.5,fill:v.online?'#1fa971':'#a2acba'}},ports:{groups:{in:{position:'left',attrs:{circle:{r:5,magnet:true,stroke:'#9ca8b8',strokeWidth:1.5,fill:'#fff'}}},out:{position:'right',attrs:{circle:{r:5,magnet:true,stroke:'#9ca8b8',strokeWidth:1.5,fill:'#fff'}}}},items:[{id:'in',group:'in'},{id:'out',group:'out'}]}})
  if(select)void selectNode(code);updateStats()
}
function addDevTask(file:DevFile){if(!graph)return;const existing=graph.getNodes().find(n=>(n.getData() as NodeData)?.devFileId===file.id);if(existing){graph.centerCell(existing);void selectNode(String(existing.id));return ElMessage.info('该开发任务已在画布中')}addGraphNode({name:stripExt(file.name),nodeType:file.fileType.toUpperCase() as NodeKind,devFileId:file.id,nodeCode:`task_${file.id}`});dirty.value=true}
function addOfflineTask(task:IntegrationTask){if(sharedMode.value)return;const existing=graph?.getNodes().find(n=>(n.getData() as NodeData)?.integrationTaskId===task.id);if(existing){graph?.centerCell(existing);void selectNode(String(existing.id));return ElMessage.info('该离线同步任务已在画布中')}addGraphNode({name:task.name,nodeType:'SEATUNNEL',configJson:JSON.stringify({integrationTaskId:task.id})});dirty.value=true}
function addSpecial(type:'SEATUNNEL'|'CONDITION'){if(sharedMode.value)return;addGraphNode({name:type==='CONDITION'?'条件分支':'SeaTunnel 节点',nodeType:type,configJson:type==='CONDITION'?JSON.stringify({expression:"status == 'SUCCESS'"}):'{}'});dirty.value=true}
function focusTask(file:DevFile){const n=graph?.getNodes().find(x=>(x.getData() as NodeData)?.devFileId===file.id);if(n){graph?.centerCell(n);void selectNode(String(n.id))}else if(!sharedMode.value)addDevTask(file)}
function clearSelection(){selectedCode.value='';selectedEdgeId.value='';selectedSchedule.value=undefined;selectedIntegrationSchedule.value=undefined;refreshSelection();graphRevision.value++}
function selectEdge(id:string){selectedEdgeId.value=id;selectedCode.value='';selectedSchedule.value=undefined;selectedIntegrationSchedule.value=undefined;refreshSelection();graphRevision.value++}
async function selectNode(code:string){selectedCode.value=code;selectedEdgeId.value='';inspectorTab.value='prop';const n=graph?.getCellById(code);if(!n?.isNode())return;const d=n.getData() as NodeData;Object.assign(nodeDraft,{name:d.name||'',nodeType:d.nodeType||'SQL',devFileId:d.devFileId,integrationTaskId:d.integrationTaskId,configJson:d.configJson||'{}',taskVersion:d.taskVersion,lifecycleStatus:d.lifecycleStatus,ownerName:d.ownerName});conditionExpression.value=String(parseConfig(d.configJson).expression||"status == 'SUCCESS'");selectedSchedule.value=undefined;selectedIntegrationSchedule.value=undefined;refreshSelection();if(d.devFileId&&selectedDevFile.value?.fileType?.toUpperCase()==='SQL'){try{selectedSchedule.value=await developmentApi.schedule(d.devFileId)}catch{}}if(d.integrationTaskId){try{selectedIntegrationSchedule.value=await integrationApi.schedule(d.integrationTaskId)}catch{}}graphRevision.value++}
async function onIntegrationTaskChange(id?:number){selectedIntegrationSchedule.value=undefined;if(id){try{selectedIntegrationSchedule.value=await integrationApi.schedule(id)}catch{}}}
function refreshSelection(){graph?.getNodes().forEach(n=>n.attr('body/stroke',String(n.id)===selectedCode.value?'#5b8def':'#dfe4eb'));graph?.getNodes().forEach(n=>n.attr('body/strokeWidth',String(n.id)===selectedCode.value?1.6:1));graph?.getEdges().forEach(e=>{const on=String(e.id)===selectedEdgeId.value;e.attr('line/stroke',on?'#5b8def':'#aeb7c4');e.attr('line/strokeWidth',on?2:1.45)})}
function canChangeEdge(edge:any){const target=graph?.getCellById(String(edge.getTargetCellId())),d=target?.isNode()?(target.getData() as NodeData):undefined,f=d?.devFileId?files.value.find(x=>x.id===d.devFileId):undefined;if(f?.fileType?.toUpperCase()==='SQL'&&f.lifecycleStatus==='ONLINE'){ElMessage.warning(`下游任务“${stripExt(f.name)}”已上线，请先下线后再修改依赖`);return false}return true}
function createsCycle(source:string,target:string){if(!graph)return false;const out=new Map<string,string[]>();graph.getNodes().forEach(n=>out.set(String(n.id),[]));graph.getEdges().forEach(e=>{const s=String(e.getSourceCellId()),t=String(e.getTargetCellId());if(s!==source||t!==target)out.get(s)?.push(t)});const stack=[target],seen=new Set<string>();while(stack.length){const x=stack.pop()!;if(x===source)return true;if(seen.has(x))continue;seen.add(x);stack.push(...(out.get(x)||[]))}return false}
function validateNewEdge(edge:any){const s=String(edge.getSourceCellId()),t=String(edge.getTargetCellId());if(!s||!t||s===t){ElMessage.warning('任务不能依赖自身');return false}if(!canChangeEdge(edge))return false;if(createsCycle(s,t)){ElMessage.warning('依赖关系会形成环路，请调整连线');return false}return true}
function applySpecialNode(){const n=graph?.getCellById(selectedCode.value);if(!n?.isNode()||selectedDevFile.value)return;const d=n.getData() as NodeData;if(d.nodeType==='SEATUNNEL'){const task=selectedIntegrationTask.value;const next={...d,name:task?.name||nodeDraft.name||'SeaTunnel 节点',integrationTaskId:nodeDraft.integrationTaskId,configJson:JSON.stringify(nodeDraft.integrationTaskId?{integrationTaskId:nodeDraft.integrationTaskId}:{})};n.setData(next);n.attr('title/text',next.name);const v=nodeVisual(next);n.attr('meta/text',v.meta);n.attr('life/fill',v.online?'#1fa971':'#a2acba')}else{const next={...d,name:nodeDraft.name||'条件分支',configJson:JSON.stringify({expression:conditionExpression.value})};n.setData(next);n.attr('title/text',next.name)}dirty.value=true;ElMessage.success('节点配置已更新');void selectNode(String(n.id))}
function removeNode(){if(sharedMode.value)return ElMessage.info('共享依赖图中的开发任务不能移除');const n=graph?.getCellById(selectedCode.value);if(!n)return;graph?.removeCell(n);clearSelection();dirty.value=true;updateStats()}
function removeSelectedEdge(){if(!selectedEdgeId.value)return;const e=graph?.getCellById(selectedEdgeId.value);if(e?.isEdge()){if(!canChangeEdge(e))return;graph?.removeCell(e);clearSelection();dirty.value=true;updateStats()}}
function payload(){const nodes=(graph?.getNodes()||[]).map(n=>{const p=n.getPosition(),d=n.getData() as NodeData;return{name:d.name,nodeType:d.nodeType,devFileId:d.devFileId,configJson:d.configJson||'{}',x:Math.round(p.x),y:Math.round(p.y),nodeCode:String(n.id)}});const edges=(graph?.getEdges()||[]).map(e=>({sourceNodeCode:String(e.getSourceCellId()),targetNodeCode:String(e.getTargetCellId())}));return{name:form.name.trim()||'开发任务依赖图',description:form.description.trim(),nodes,edges}}
async function save(){if(sharedMode.value){saving.value=true;try{const saved=await workflowApi.saveDevelopmentGraph(payload());sharedGraph.value=saved;current.value=saved;await loadTasks();initGraph(saved);dirty.value=false;ElMessage.success('开发任务依赖已同步到数据开发')}catch(e){ElMessage.error(msg(e))}finally{saving.value=false}return}if(!form.name.trim())return ElMessage.warning('请输入工作流名称');if(!graph?.getNodes().length)return ElMessage.warning('请至少添加一个任务节点');saving.value=true;try{const saved=current.value?await workflowApi.update(current.value.id,payload()):await workflowApi.create(payload());current.value=saved;await Promise.all([load(),loadSharedGraph(),loadTasks()]);current.value=await workflowApi.get(saved.id);form.name=current.value.name;form.description=current.value.description||'';initGraph(current.value);dirty.value=false;ElMessage.success('工作流已保存')}catch(e){ElMessage.error(msg(e))}finally{saving.value=false}}
async function publish(){if(sharedMode.value)return ElMessage.info('开发任务依赖图无需单独发布');if(dirty.value||!current.value){await save();if(!current.value||dirty.value)return}try{const req=await releaseApi.request({resourceType:'WORKFLOW',resourceId:current.value.id,resourceName:form.name,requestedVersion:current.value.publishedVersion+1});if(req.status==='RELEASED')ElMessage.success('工作流已发布');else if(req.status==='PENDING_APPROVAL')ElMessage.info('发布申请已提交，等待审批');else ElMessage.info(`发布状态：${req.status}`);await load();current.value=await workflowApi.get(current.value.id);initGraph(current.value)}catch(e){ElMessage.error(msg(e))}}
async function run(){if(sharedMode.value)return ElMessage.info('开发任务依赖图由各任务自己的调度执行');if(!current.value)return ElMessage.warning('请先保存工作流');try{await workflowApi.run(current.value.id);ElMessage.success('运行实例已提交')}catch(e){ElMessage.error(msg(e))}}
async function runRow(r:WorkflowView){if(r.id===0)return ElMessage.info('共享依赖图由开发任务调度运行');try{await workflowApi.run(r.id);ElMessage.success('运行实例已提交')}catch(e){ElMessage.error(msg(e))}}
async function refreshAll(){await Promise.all([load(),loadSharedGraph(),loadTasks()])}
function autoLayout(){if(!graph)return;const nodes=graph.getNodes(),edges=graph.getEdges(),indegree=new Map<string,number>(),out=new Map<string,string[]>();nodes.forEach(n=>{indegree.set(String(n.id),0);out.set(String(n.id),[])});edges.forEach(e=>{const s=String(e.getSourceCellId()),t=String(e.getTargetCellId());if(indegree.has(t)&&out.has(s)){indegree.set(t,(indegree.get(t)||0)+1);out.get(s)!.push(t)}});const queue=[...indegree.entries()].filter(([,v])=>v===0).map(([k])=>k),level=new Map<string,number>();queue.forEach(k=>level.set(k,0));while(queue.length){const id=queue.shift()!,l=level.get(id)||0;for(const n of out.get(id)||[]){level.set(n,Math.max(level.get(n)||0,l+1));indegree.set(n,(indegree.get(n)||1)-1);if(indegree.get(n)===0)queue.push(n)}}nodes.forEach(n=>{if(!level.has(String(n.id)))level.set(String(n.id),0)});const layers=new Map<number,string[]>();for(const [id,l] of level)layers.set(l,[...(layers.get(l)||[]),id]);for(const [l,ids] of layers)ids.forEach((id,i)=>{const cell=graph?.getCellById(id);if(cell?.isNode())cell.setPosition(80+l*270,95+i*130)});if(!sharedMode.value)dirty.value=true;updateStats();setTimeout(()=>fit(),0)}
function updateStats(){if(!graph){Object.assign(stats,{nodes:0,edges:0,roots:0,leaves:0});return}const nodes=graph.getNodes(),edges=graph.getEdges(),ins=new Set(edges.map(e=>String(e.getTargetCellId()))),outs=new Set(edges.map(e=>String(e.getSourceCellId())));Object.assign(stats,{nodes:nodes.length,edges:edges.length,roots:nodes.filter(n=>!ins.has(String(n.id))).length,leaves:nodes.filter(n=>!outs.has(String(n.id))).length});graphRevision.value++}
function zoom(delta:number){if(!graph)return;graphScale.value=Math.max(.7,Math.min(1.5,Math.round((graphScale.value+delta)*10)/10));graph.zoomTo(graphScale.value)}
function fit(){graph?.zoomToFit({padding:68,maxScale:1});graphScale.value=1}
function openDevelopment(){if(nodeDraft.devFileId)void router.push({path:'/development/workspace',query:{fileId:String(nodeDraft.devFileId)}})}
function onKeydown(e:KeyboardEvent){if((e.key==='Delete'||e.key==='Backspace')&&selectedEdgeId.value&&!['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement)?.tagName)){e.preventDefault();removeSelectedEdge()}}

onMounted(()=>{void boot();window.addEventListener('keydown',onKeydown)})
onBeforeUnmount(()=>{graph?.dispose();window.removeEventListener('keydown',onKeydown)})
</script>

<template>
<div class="workflow-page">
  <section v-if="!editorOpen" class="list-page">
    <div class="pagehead"><div><h1>工作流</h1><p>统一编排开发任务和离线同步任务，依赖关系可在画布中手工连接与删除。</p></div><div class="page-actions"><button class="btn" @click="refreshAll">刷新</button><button class="btn primary" @click="newWorkflow">+ 新建工作流</button></div></div>
    <div class="card list-card">
      <div class="list-toolbar"><el-input v-model="listSearch" :prefix-icon="Search" clearable placeholder="搜索工作流名称 / 编码"/><el-select v-model="statusFilter"><el-option label="全部状态" value="ALL"/><el-option label="草稿" value="DRAFT"/><el-option label="已发布" value="PUBLISHED"/><el-option label="运行中" value="RUNNING"/><el-option label="已同步" value="SYNCED"/></el-select><span class="list-count">{{workflowRows.length}} 个工作流</span></div>
      <div class="table-wrap">
        <table><thead><tr><th style="width:28%">工作流名称</th><th style="width:13%">状态</th><th style="width:10%">版本</th><th style="width:10%">任务数</th><th style="width:10%">依赖数</th><th style="width:17%">最近修改</th><th style="width:12%">操作</th></tr></thead>
        <tbody><tr v-for="r in workflowRows" :key="r.workflowCode"><td><span class="wf-name" @click="edit(r)">{{r.name}}</span><span class="wf-code">{{r.workflowCode}}</span></td><td><span class="status-tag"><i :class="['status-dot',statusClass(r.status)]"></i>{{statusLabel(r.status)}}</span></td><td>{{r.id===0?'实时':(r.publishedVersion?`V${r.publishedVersion}`:'草稿')}}</td><td>{{r.nodes.length}}</td><td>{{r.edges.length}}</td><td>{{r.id===0?'实时同步':fmt(r.updatedAt)}}</td><td><span class="link" @click="edit(r)">打开</span><span class="sep">·</span><span class="link" @click="runRow(r)">运行</span></td></tr>
        <tr v-if="!workflowRows.length"><td colspan="7"><div class="table-empty">没有匹配的工作流</div></td></tr></tbody></table>
      </div>
    </div>
  </section>

  <section v-else class="card editor-card">
    <header class="editor-head"><button class="back" @click="closeEditor">‹</button><div class="editor-title"><div class="title-row"><strong>{{sharedMode?'开发任务依赖图':(current?form.name||current.name:'新建工作流')}}</strong><div class="chips"><span class="chip">{{current?.workflowCode||'wf_new_draft'}}</span><span :class="['chip',current?.status==='PUBLISHED'||sharedMode?'ok':'warn']">{{sharedMode?'已同步':statusLabel(current?.status)}}</span><span class="chip">{{sharedMode?'实时':(current?.publishedVersion?`V${current.publishedVersion}`:'草稿')}}</span></div></div><div class="title-sub">{{sharedMode?'开发任务调度依赖与工作流共享；调整依赖后保存即可同步回数据开发。':'画布依赖由用户手工连接；删除连线后保存即可同步工作流依赖。'}}</div></div><div class="editor-actions"><button class="btn" @click="autoLayout">自动布局</button><button class="btn" :disabled="saving" @click="save">{{saving?'保存中…':(sharedMode?'保存依赖':'保存')}}</button><button v-if="!sharedMode&&current" class="btn" @click="run">运行</button><button v-if="!sharedMode" class="btn primary" @click="publish">发布</button></div></header>
    <div class="meta"><template v-if="!sharedMode"><input v-model="form.name" placeholder="工作流名称"><input v-model="form.description" placeholder="工作流描述（可选）"></template><template v-else><div class="shared-title">开发任务 SQL 全局 DAG</div><div class="shared-desc">所有任务和依赖直接读取数据开发配置</div></template><div class="sync"><span class="status-dot green"></span>{{sharedMode?'实时读取 dev_file_schedule_dependency':'开发任务调度依赖与工作流共享'}}</div></div>
    <div class="editor-grid">
      <aside class="left-panel"><div class="panel-head"><strong>任务库</strong><span>{{taskCount}} 项</span></div><div class="task-search"><el-input v-model="taskSearch" :prefix-icon="Search" clearable placeholder="搜索任务 / 负责人 / 同步任务"/></div><div class="filters"><button v-for="f in ([['ALL','全部'],['DEV','开发任务'],['OFFLINE','离线同步'],['SQL','SQL'],['PYTHON','Python'],['SHELL','Shell']] as const)" :key="f[0]" :class="{on:taskFilter===f[0]}" :disabled="sharedMode&&f[0]==='OFFLINE'" @click="taskFilter=f[0]">{{f[1]}}</button></div><div class="task-list"><template v-if="filteredDevTasks.length"><div class="section-label">开发任务</div><button v-for="f in filteredDevTasks" :key="'d'+f.id" class="task-item" @click="sharedMode?focusTask(f):addDevTask(f)"><span class="task-ico">{{f.fileType==='PYTHON'?'PY':f.fileType==='SHELL'?'SH':'SQL'}}</span><span class="task-main"><b>{{stripExt(f.name)}}</b><small>V{{f.currentVersion}} · {{f.ownerName||'—'}} · {{lifecycleLabel(f.lifecycleStatus)}}</small></span><i :class="['status-dot',f.lifecycleStatus==='ONLINE'?'green':'gray']"></i></button></template><template v-if="filteredOfflineTasks.length"><div class="section-label offline-label">离线同步任务</div><button v-for="t in filteredOfflineTasks" :key="'o'+t.id" class="task-item" @click="addOfflineTask(t)"><span class="task-ico st">ST</span><span class="task-main"><b>{{t.name}}</b><small>{{integrationRoute(t)}}</small></span><i :class="['status-dot',t.lifecycleStatus==='ONLINE'||t.status==='ENABLED'?'green':'gray']"></i></button></template><div v-if="!taskCount" class="task-empty">没有匹配任务</div><template v-if="!sharedMode"><div class="task-divider"></div><div class="section-label">编排节点</div><button class="task-item" @click="addSpecial('CONDITION')"><span class="task-ico condition">◇</span><span class="task-main"><b>条件分支</b><small>仅属于当前工作流</small></span></button><button class="task-item" @click="addSpecial('SEATUNNEL')"><span class="task-ico st">ST</span><span class="task-main"><b>SeaTunnel 节点</b><small>点击后绑定已配置离线同步任务</small></span></button></template></div></aside>

      <main class="canvas-panel"><div class="canvas-help">从节点右侧连接点拖到下游节点左侧；点击连线选中，Delete 删除；双击连线也可删除。</div><div class="canvas-tools"><button @click="zoom(-.1)">−</button><span>{{Math.round(graphScale*100)}}%</span><button @click="zoom(.1)">＋</button><button title="适应画布" @click="fit">⌂</button></div><div ref="canvasRef" class="canvas-host"></div><div class="canvas-status"><span>{{stats.nodes}} 个节点</span><span>{{stats.edges}} 条依赖</span><span>{{stats.roots}} 个起点</span><span>{{stats.leaves}} 个末端</span><span class="selected-info">{{selectedEdgeId?'已选中 1 条连线':selectedCode?'已选中节点':'未选择'}}</span></div></main>

      <aside class="right-panel"><div class="panel-head"><strong>节点详情</strong><span>{{selectedEdgeId?'依赖连线':selectedCode?nodeDraft.name:'未选择'}}</span></div><div v-if="!selectedCode&&!selectedEdgeId" class="empty-inspector"><div class="empty-ico">⌁</div><b>选择节点或连线</b><span>查看属性、调度、依赖，或删除已选依赖连线。</span></div>
        <div v-else-if="selectedEdgeId" class="edge-box"><div class="block-title"><strong>依赖连线</strong></div><p><b>{{selectedEdgeInfo?.source}}</b> → <b>{{selectedEdgeInfo?.target}}</b></p><p>当前依赖由画布维护。删除后保存，即表示移除该上下游关系。</p><button class="btn danger full" @click="removeSelectedEdge">删除依赖</button><small>也可以按 Delete / Backspace，或双击画布上的连线删除。</small></div>
        <template v-else><div class="inspector-tabs"><button :class="{on:inspectorTab==='prop'}" @click="inspectorTab='prop'">属性</button><button :class="{on:inspectorTab==='schedule'}" @click="inspectorTab='schedule'">调度</button><button :class="{on:inspectorTab==='dep'}" @click="inspectorTab='dep'">依赖</button></div><div class="inspector-scroll">
          <div v-if="inspectorTab==='prop'">
            <template v-if="selectedDevFile"><div class="hero"><span class="task-ico large">{{selectedDevFile.fileType==='PYTHON'?'PY':selectedDevFile.fileType==='SHELL'?'SH':'SQL'}}</span><div><b>{{stripExt(selectedDevFile.name)}}</b><small>{{selectedDevFile.description||'开发任务'}}</small></div></div><div class="block"><div class="block-title"><strong>基本信息</strong><span>开发任务</span></div><div class="kv"><span>任务版本</span><b>V{{selectedDevFile.currentVersion}}</b><span>生命周期</span><b>{{lifecycleLabel(selectedDevFile.lifecycleStatus)}}</b><span>负责人</span><b>{{selectedDevFile.ownerName||'—'}}</b><span>任务类型</span><b>{{typeLabel(selectedDevFile.fileType)}}</b><span>节点编码</span><b class="mono">{{selectedCode}}</b></div></div><div v-if="selectedDevFile.lifecycleStatus==='ONLINE'" class="notice">任务已上线。查看依赖不受影响，但修改指向该任务的上游关系时仍沿用上线保护规则。</div><div class="row-btns"><button class="btn" @click="openDevelopment">在数据开发中打开</button><button v-if="!sharedMode" class="btn danger" @click="removeNode">移除节点</button></div></template>
            <template v-else-if="nodeDraft.nodeType==='SEATUNNEL'"><div class="hero"><span class="task-ico st large">ST</span><div><b>{{selectedIntegrationTask?.name||nodeDraft.name||'SeaTunnel 节点'}}</b><small>{{selectedIntegrationTask?'已绑定离线同步任务':'选择一个已经配置好的离线同步任务'}}</small></div></div><div class="block"><div class="block-title"><strong>绑定离线同步任务</strong><span>已配置任务</span></div><label class="field-label">离线同步任务</label><el-select v-model="nodeDraft.integrationTaskId" clearable filterable placeholder="请选择离线同步任务" @change="onIntegrationTaskChange" style="width:100%"><el-option v-for="t in integrationTasks" :key="t.id" :label="t.name" :value="t.id"/></el-select><div v-if="selectedIntegrationTask" class="sync-card"><b>{{selectedIntegrationTask.name}}</b><small>来源：{{integrationRoute(selectedIntegrationTask).split(' → ')[0]}}<br>目标：{{integrationRoute(selectedIntegrationTask).split(' → ')[1]||'—'}}<br>模式：{{integrationMode(selectedIntegrationTask)}}<br>状态：{{selectedIntegrationTask.lifecycleStatus==='ONLINE'?'已上线':selectedIntegrationTask.status}}</small></div></div><div class="row-btns"><button class="btn primary" @click="applySpecialNode">应用绑定</button><button class="btn danger" @click="removeNode">移除节点</button></div></template>
            <template v-else><div class="hero"><span class="task-ico condition large">◇</span><div><b>{{nodeDraft.name||'条件分支'}}</b><small>工作流条件控制节点</small></div></div><div class="block"><label class="field-label">节点名称</label><el-input v-model="nodeDraft.name"/><label class="field-label gap">条件表达式</label><el-input v-model="conditionExpression" type="textarea" :rows="5"/></div><div class="row-btns"><button class="btn primary" @click="applySpecialNode">应用配置</button><button class="btn danger" @click="removeNode">移除节点</button></div></template>
          </div>
          <div v-else-if="inspectorTab==='schedule'">
            <template v-if="selectedDevFile&&selectedSchedule"><div class="block top"><div class="block-title"><strong>调度配置</strong><span>与数据开发共享</span></div><div class="kv"><span>状态</span><b>{{selectedSchedule.enabled?'已启用':'未启用'}}</b><span>周期</span><b>{{cycleLabel(selectedSchedule.cycleType)}} {{selectedSchedule.executionTime||''}}</b><span>Cron</span><b class="mono">{{selectedSchedule.cronExpression}}</b><span>Database</span><b>{{selectedSchedule.databaseName||'—'}}</b></div></div></template>
            <template v-else-if="selectedDevFile"><div class="block top muted">当前 {{typeLabel(selectedDevFile.fileType)}} 任务未配置数据开发调度。</div></template>
            <template v-else-if="selectedIntegrationTask"><div class="block top"><div class="block-title"><strong>离线同步信息</strong><span>{{selectedIntegrationTask.lifecycleStatus==='ONLINE'?'已上线':selectedIntegrationTask.status}}</span></div><div class="kv"><span>同步模式</span><b>{{integrationMode(selectedIntegrationTask)}}</b><span>来源 → 目标</span><b>{{integrationRoute(selectedIntegrationTask)}}</b><span>调度状态</span><b>{{selectedIntegrationSchedule?.enabled?'已启用':'未启用'}}</b><span>Cron</span><b class="mono">{{selectedIntegrationSchedule?.cronExpression||'—'}}</b><span>时区</span><b>{{selectedIntegrationSchedule?.timezone||'—'}}</b></div></div></template>
            <div v-else class="block top muted">条件节点不直接配置调度周期。</div>
          </div>
          <div v-else class="dep-tab"><div class="block top"><div class="block-title"><strong>上游依赖</strong><span>{{selectedDependencies.ups.length}} 个</span></div><div v-if="selectedDependencies.ups.length" class="pill-box"><span v-for="x in selectedDependencies.ups" :key="x" class="dep-pill">{{x}}</span></div><span v-else class="muted">暂无上游</span></div><div class="block"><div class="block-title"><strong>下游任务</strong><span>{{selectedDependencies.downs.length}} 个</span></div><div v-if="selectedDependencies.downs.length" class="pill-box"><span v-for="x in selectedDependencies.downs" :key="x" class="dep-pill">{{x}}</span></div><span v-else class="muted">暂无下游</span></div></div>
        </div></template>
      </aside>
    </div>
  </section>
</div>
</template>
<style scoped>
.workflow-page{height:calc(100vh - var(--ds-topbar));min-height:680px;padding:16px;background:#f5f7fb;color:#182235;overflow:hidden}.list-page{height:100%;display:flex;flex-direction:column}.pagehead{display:flex;align-items:flex-start;padding:4px 2px 14px}.pagehead h1{margin:0;font-size:27px;line-height:1.2}.pagehead p{margin:7px 0 0;color:#5f6f86;font-size:13px}.page-actions{margin-left:auto;display:flex;gap:8px}.btn{height:36px;padding:0 14px;border:1px solid #e4eaf2;border-radius:9px;background:#fff;color:#34465f;cursor:pointer;font-size:13px}.btn:hover{background:#f8fbff}.btn:disabled{opacity:.55;cursor:not-allowed}.btn.primary{background:#2f6fed;border-color:#2f6fed;color:#fff}.btn.danger{color:#d84b4b;border-color:#efcece}.btn.full{width:100%}.card{background:#fff;border:1px solid #e4eaf2;border-radius:14px;box-shadow:0 8px 24px rgba(20,38,65,.06);overflow:hidden}.list-card{flex:1;min-height:0;display:flex;flex-direction:column;box-shadow:none}.list-toolbar{height:54px;display:flex;align-items:center;gap:10px;padding:0 15px;border-bottom:1px solid #edf1f6}.list-toolbar :deep(.el-input){width:300px}.list-toolbar :deep(.el-select){width:125px}.list-toolbar :deep(.el-input__wrapper),.list-toolbar :deep(.el-select__wrapper){min-height:37px;border-radius:9px;box-shadow:0 0 0 1px #e4eaf2 inset}.list-count{margin-left:auto;color:#8d99aa;font-size:12px}.table-wrap{flex:1;overflow:auto}table{width:100%;border-collapse:collapse;table-layout:fixed}th{height:43px;padding:0 15px;text-align:left;font-size:12px;color:#5f6f86;background:#fbfcfe;border-bottom:1px solid #e4eaf2}td{height:56px;padding:8px 15px;border-bottom:1px solid #edf1f6;color:#34445a;font-size:13px}tbody tr:hover td{background:#fafcff}.wf-name{display:block;font-weight:700;cursor:pointer}.wf-name:hover{color:#2f6fed}.wf-code{display:block;margin-top:4px;font:11px ui-monospace,Consolas;color:#8d99aa}.status-tag{display:inline-flex;align-items:center;gap:6px;height:27px;padding:0 9px;border:1px solid #e4eaf2;border-radius:999px;font-size:12px}.status-dot{display:inline-block;width:7px;height:7px;border-radius:50%;flex:none}.status-dot.green{background:#1fa971}.status-dot.blue{background:#2f6fed}.status-dot.orange{background:#d18a16}.status-dot.gray{background:#a2acba}.link{color:#2f6fed;cursor:pointer;font-weight:600}.danger-link{color:#d84b4b;cursor:pointer}.sep{color:#ccd4df;margin:0 7px}.table-empty{height:160px;display:grid;place-items:center;color:#8d99aa}
.editor-card{height:100%;display:grid;grid-template-rows:62px 52px minmax(0,1fr)}.editor-head{display:flex;align-items:center;gap:12px;padding:0 14px;border-bottom:1px solid #edf1f6}.back{width:34px;height:34px;border:1px solid #e4eaf2;border-radius:9px;background:#fff;font-size:21px;color:#52647c;cursor:pointer}.back:hover{background:#f8fbff}.editor-title{min-width:0}.title-row{display:flex;align-items:center}.title-row strong{font-size:17px;max-width:360px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.chips{display:flex;gap:7px;margin-left:8px}.chip{height:24px;padding:0 9px;border:1px solid #e4eaf2;border-radius:999px;display:inline-flex;align-items:center;font-size:11px;color:#5f6f86;background:#f8fafc}.chip.warn{color:#99630a;background:#fff7e8;border-color:#efd9aa}.chip.ok{color:#16794f;background:#edf9f4;border-color:#caeadb}.title-sub{margin-top:4px;color:#8d99aa;font-size:11px}.editor-actions{margin-left:auto;display:flex;gap:7px}.meta{display:grid;grid-template-columns:250px minmax(300px,480px) 1fr;gap:10px;align-items:center;padding:7px 14px;background:#fbfcfe;border-bottom:1px solid #edf1f6}.meta input{height:36px;border:1px solid #e4eaf2;border-radius:9px;padding:0 11px;color:#182235;background:#fff}.shared-title{font-size:13px;font-weight:700;color:#314056}.shared-desc{font-size:11px;color:#8d99aa}.sync{justify-self:end;display:flex;align-items:center;gap:7px;color:#5f6f86;font-size:11px;white-space:nowrap}
.editor-grid{display:grid;grid-template-columns:286px minmax(0,1fr) 350px;min-height:0}.left-panel,.right-panel{background:#fff;min-height:0;display:flex;flex-direction:column}.left-panel{border-right:1px solid #edf1f6}.right-panel{border-left:1px solid #edf1f6}.panel-head{height:49px;display:flex;align-items:center;justify-content:space-between;padding:0 14px;border-bottom:1px solid #edf1f6;flex:0 0 auto}.panel-head strong{font-size:13px}.panel-head span{font-size:11px;color:#8d99aa;max-width:190px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.task-search{padding:10px 11px 8px}.task-search :deep(.el-input__wrapper){min-height:36px;border-radius:9px;box-shadow:0 0 0 1px #e4eaf2 inset}.filters{display:flex;gap:6px;padding:0 11px 9px;flex-wrap:wrap}.filters button{height:29px;padding:0 9px;border:1px solid #e4eaf2;border-radius:8px;background:#fff;color:#5f6f86;cursor:pointer;font-size:11px}.filters button.on{background:#edf4ff;color:#2f6fed;border-color:#cfe0fb;font-weight:700}.filters button:disabled{opacity:.45;cursor:not-allowed}.task-list{flex:1;min-height:0;overflow:auto;padding:0 8px 12px}.section-label{padding:9px 6px 7px;color:#8d99aa;font-size:11px;font-weight:700}.offline-label{margin-top:5px}.task-item{width:100%;min-height:58px;display:flex;align-items:center;gap:9px;border:1px solid transparent;border-radius:11px;background:#fff;padding:8px 9px;text-align:left;cursor:pointer}.task-item:hover{background:#f8fbff;border-color:#d9e6f7}.task-ico{width:34px;height:34px;border-radius:9px;border:1px solid #d2e1f8;background:#f3f8ff;color:#2f6fed;display:grid;place-items:center;font-size:10px;font-weight:800;flex:none}.task-ico.st{color:#6d55d8;background:#f7f5ff;border-color:#e0d9fa}.task-ico.condition{color:#687689;background:#f8fafc;border-style:dashed;border-color:#cad2dd}.task-ico.large{width:42px;height:42px;font-size:11px}.task-main{flex:1;min-width:0}.task-main b,.task-main small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.task-main b{font-size:12px;color:#2d3b50}.task-main small{margin-top:4px;color:#8d99aa;font-size:10px}.task-divider{height:1px;background:#edf1f6;margin:9px 6px}.task-empty{padding:18px 8px;color:#8d99aa;font-size:11px;text-align:center}
.canvas-panel{position:relative;min-width:0;min-height:0;background:#f7f8fb}.canvas-help{position:absolute;left:13px;top:11px;z-index:6;padding:8px 10px;border:1px solid #e1e6ee;border-radius:8px;background:rgba(255,255,255,.94);color:#75839a;font-size:11px}.canvas-tools{position:absolute;right:13px;top:11px;z-index:6;display:flex;align-items:center;gap:6px;padding:6px;border:1px solid #e1e6ee;border-radius:9px;background:#fff;box-shadow:0 3px 12px rgba(23,41,70,.05)}.canvas-tools button{height:30px;min-width:30px;border:1px solid #e3e8ef;border-radius:7px;background:#fff;cursor:pointer;color:#52647c}.canvas-tools span{font-size:11px;color:#5f6f86;padding:0 4px;min-width:42px;text-align:center}.canvas-host{position:absolute;inset:0 0 34px 0}.canvas-status{height:34px;position:absolute;left:0;right:0;bottom:0;border-top:1px solid #edf1f6;background:#fff;display:flex;align-items:center;gap:15px;padding:0 12px;color:#5f6f86;font-size:10px}.selected-info{margin-left:auto}.canvas-panel :deep(.x6-node){filter:drop-shadow(0 3px 5px rgba(26,39,61,.07))}.canvas-panel :deep(.x6-node:hover rect[selector="body"]){stroke:#c5d0dd}.canvas-panel :deep(.x6-port-body:hover){stroke:#5b8def;fill:#f5f8ff}
.empty-inspector{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;color:#8d99aa;gap:8px;padding:20px}.empty-ico{width:48px;height:48px;border:1px solid #e4eaf2;border-radius:15px;display:grid;place-items:center;background:#f6f9fd;color:#708198;font-size:20px}.empty-inspector b{font-size:12px;color:#5f6f86}.empty-inspector span{font-size:10px}.inspector-tabs{display:flex;gap:7px;padding:11px 13px;border-bottom:1px solid #edf1f6}.inspector-tabs button{height:30px;padding:0 10px;border:1px solid #e4eaf2;border-radius:8px;background:#fff;color:#5f6f86;font-size:11px;cursor:pointer}.inspector-tabs button.on{background:#edf4ff;border-color:#cfe0fb;color:#2f6fed;font-weight:700}.inspector-scroll{flex:1;overflow:auto;padding-bottom:14px}.hero{margin:14px;border:1px solid #e4eaf2;border-radius:12px;background:#fbfcfe;padding:12px;display:flex;gap:10px}.hero b{display:block;font-size:14px}.hero small{display:block;margin-top:4px;color:#8d99aa;font-size:10px}.block{padding:0 14px 16px}.block.top{padding-top:15px}.block-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.block-title strong{font-size:12px}.block-title span{font-size:10px;color:#8d99aa}.kv{display:grid;grid-template-columns:86px 1fr;gap:9px 10px;font-size:11px}.kv>span{color:#8d99aa}.kv>b{font-weight:500;color:#314056;min-width:0}.mono{font-family:ui-monospace,Consolas;font-size:10px;word-break:break-all}.notice{margin:0 14px 14px;padding:9px 10px;border:1px solid #d8ebdf;border-radius:10px;background:#f4fbf7;color:#4c6d5a;font-size:10px;line-height:1.6}.row-btns{display:flex;gap:8px;padding:0 14px 14px}.row-btns .btn{flex:1}.field-label{display:block;margin:0 0 6px;color:#5f6f86;font-size:10px;font-weight:700}.field-label.gap{margin-top:12px}.sync-card{border:1px solid #e4eaf2;border-radius:11px;background:#fbfcfe;padding:10px;margin-top:9px}.sync-card b{display:block;font-size:11px}.sync-card small{display:block;margin-top:4px;color:#8d99aa;font-size:10px;line-height:1.55}.pill-box{display:flex;gap:7px;flex-wrap:wrap}.dep-pill{padding:5px 8px;border:1px solid #e4eaf2;border-radius:999px;background:#fff;color:#44546a;font-size:10px}.muted{color:#8d99aa;font-size:11px}.edge-box{padding:15px}.edge-box p{color:#5f6f86;font-size:11px;line-height:1.7}.edge-box small{display:block;margin-top:10px;color:#8d99aa;font-size:10px;line-height:1.6}
:deep(.el-input__wrapper),:deep(.el-select__wrapper),:deep(.el-textarea__inner){box-shadow:0 0 0 1px #e4eaf2 inset;border-radius:9px}.right-panel :deep(.el-select__wrapper){min-height:36px}.right-panel :deep(.el-textarea__inner){padding:9px 10px}.right-panel :deep(.el-input__wrapper){min-height:36px}@media(max-width:1300px){.editor-grid{grid-template-columns:260px minmax(0,1fr) 330px}.meta{grid-template-columns:220px minmax(260px,380px) 1fr}.title-sub{display:none}}
</style>
